import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test, type APIRequestContext } from "@playwright/test";

// Slidev deck question switching e2e:
//
// Two scenarios in serial:
//   1. Signed-in presenter navigates between Q1 (slide 3) and Q2 (slide 4) with
//      keyboard. PollPanel's IntersectionObserver fires /activate POSTs as the
//      slides scroll into view; we assert the backend reflects the active
//      question after each move. CORS must stay clean throughout.
//   2. Anonymous viewer follows the active question driven externally via the
//      admin API. PollPanel must not POST /activate or /close because the deck
//      is unauthenticated; we assert empty call lists for those routes plus a
//      clean CORS console.

const SLIDEV = "http://localhost:3030";
const BACKEND = "http://localhost:8080";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_TS_PATH = path.resolve(__dirname, "../../slidev-demo/data.ts");

type SeededData = { pollId: string; q1Id: string; q2Id: string; slug: string };

async function xsrfHeaders(
  request: APIRequestContext,
  baseURL: string
): Promise<Record<string, string>> {
  const state = await request.storageState();
  const origin = new URL(baseURL);
  const cookie = state.cookies.find(
    (c) =>
      c.name === "XSRF-TOKEN" &&
      (c.domain === origin.hostname || c.domain === `.${origin.hostname}`)
  );
  return cookie ? { "X-XSRF-TOKEN": decodeURIComponent(cookie.value) } : {};
}

async function loginAsAlice(request: APIRequestContext) {
  const res = await request.post("/api/admin/login", {
    data: { username: "alice", password: "correct-horse" },
    headers: { "content-type": "application/json" }
  });
  expect(res.status(), "alice login").toBeLessThan(300);
}

async function ensureAdminBootstrapped(request: APIRequestContext) {
  const status = await request.get("/api/admin/setup/status");
  expect(status.status(), "setup status probe").toBe(200);
  const { setupRequired } = (await status.json()) as { setupRequired: boolean };
  if (!setupRequired) return;
  const res = await request.post("/api/admin/setup", {
    headers: { "content-type": "application/json" },
    data: { username: "alice", password: "correct-horse" }
  });
  if (!res.ok()) {
    throw new Error(`first-run setup failed: ${res.status()} ${await res.text()}`);
  }
}

async function seedPoll(request: APIRequestContext, baseURL: string): Promise<SeededData> {
  const headers = {
    "content-type": "application/json",
    ...(await xsrfHeaders(request, baseURL))
  };
  const slug = `e2e-switch-${Date.now()}`;
  const res = await request.post("/api/admin/polls", {
    headers,
    data: {
      title: "Deck Question Switch E2E Poll",
      slug,
      allowedOrigins: [SLIDEV],
      questions: [
        {
          prompt: "Which JVM for the workshop?",
          options: [{ label: "OpenJDK 21" }, { label: "GraalVM" }, { label: "Azul Zulu" }]
        },
        {
          prompt: "Favourite build tool?",
          options: [{ label: "Maven" }, { label: "Gradle" }, { label: "Bazel" }]
        }
      ]
    }
  });
  expect(res.status(), "create poll").toBe(201);
  const body = await res.json();
  const pollId: string = body.id;
  const q1Id: string = body.questions[0].id;
  const q2Id: string = body.questions[1].id;

  fs.writeFileSync(
    DATA_TS_PATH,
    [
      `// Generated by e2e spec at ${new Date().toISOString()}.`,
      `// Safe to regenerate; checked in only as a placeholder stub.`,
      ``,
      `export const pollServer = "${BACKEND}";`,
      `export const pollSlug = "${slug}";`,
      `export const pollId = "${pollId}";`,
      `export const q1Id = "${q1Id}";`,
      `export const q2Id = "${q2Id}";`,
      ``
    ].join("\n")
  );

  return { pollId, q1Id, q2Id, slug };
}

async function deletePoll(request: APIRequestContext, baseURL: string, pollId: string) {
  const headers = {
    "content-type": "application/json",
    ...(await xsrfHeaders(request, baseURL))
  };
  const res = await request.delete(`/api/admin/polls/${pollId}`, { headers });
  expect([204, 404], `delete poll ${pollId}`).toContain(res.status());
}

async function fetchActiveQuestionId(
  request: APIRequestContext,
  baseURL: string,
  pollId: string
): Promise<string | null> {
  const res = await request.get(`/api/admin/polls/${pollId}`, {
    headers: { ...(await xsrfHeaders(request, baseURL)) }
  });
  expect(res.status(), `GET /api/admin/polls/${pollId}`).toBe(200);
  const body = (await res.json()) as { activeQuestionId: string | null };
  return body.activeQuestionId;
}

async function adminOpen(
  request: APIRequestContext,
  baseURL: string,
  pollId: string,
  questionId: string
) {
  const headers = {
    "content-type": "application/json",
    ...(await xsrfHeaders(request, baseURL))
  };
  const res = await request.post(`/api/admin/polls/${pollId}/open`, {
    headers,
    data: { questionId }
  });
  expect(res.status(), `open question ${questionId}`).toBe(200);
}

async function adminClose(request: APIRequestContext, baseURL: string, pollId: string) {
  const headers = {
    "content-type": "application/json",
    ...(await xsrfHeaders(request, baseURL))
  };
  const res = await request.post(`/api/admin/polls/${pollId}/close`, { headers });
  expect([200, 409], `close active question on ${pollId}`).toContain(res.status());
}

test.describe.configure({ mode: "serial" });
test.describe("slidev deck question switching", () => {
  let seededData: SeededData;

  test.beforeAll(async ({ playwright, baseURL }) => {
    const request = await playwright.request.newContext({ baseURL });
    await ensureAdminBootstrapped(request);
    await loginAsAlice(request);
    seededData = await seedPoll(request, baseURL!);
    await request.dispose();
  });

  test.afterAll(async ({ playwright, baseURL }) => {
    const request = await playwright.request.newContext({ baseURL });
    await loginAsAlice(request);
    await deletePoll(request, baseURL!, seededData.pollId);
    await request.dispose();
  });

  test("signed-in presenter: keyboard navigation switches active question and stays CORS-clean", async ({
    page,
    playwright,
    baseURL
  }) => {
    const pageErrors: string[] = [];
    const corsConsoleErrors: string[] = [];
    page.on("pageerror", (err) => {
      // Slidev's wake-lock plugin throws NotAllowedError in headless Chromium because
      // wakeLock requires a focused page. It's a slidev-runtime concern, not a defect
      // in the deck under test — filter it so the CORS-clean assertion stays useful.
      if (/Wake Lock/i.test(err.message)) return;
      pageErrors.push(err.message);
    });
    page.on("console", (msg) => {
      if (msg.type() !== "error") return;
      if (/CORS|cross-origin|Access-Control/i.test(msg.text())) {
        corsConsoleErrors.push(msg.text());
      }
    });

    const admin = await playwright.request.newContext({ baseURL });
    await loginAsAlice(admin);

    await page.goto(`${SLIDEV}/3`);
    await expect(page.getByTestId("poll-results").first()).toBeVisible({ timeout: 30_000 });

    // Fresh sign-in: clear any persisted deck-auth token, then drive the nav UI.
    await page.evaluate(() => window.localStorage.removeItem("slidev-polls:deck-auth"));
    await page.getByTestId("deck-auth-nav-trigger").click();
    await page.getByTestId("deck-auth-username").fill("alice");
    await page.getByTestId("deck-auth-password").fill("correct-horse");
    await page.getByTestId("deck-auth-control").getByRole("button", { name: "sign in" }).click();
    await expect(page.getByTestId("deck-auth-nav-trigger")).toContainText("deck", {
      timeout: 20_000
    });

    // After sign-in the Q1 slide is already visible, so PollPanel's slide-display branch never
    // fired Q1's activate (it only activates on a display:none → "" transition). Drive real slide
    // changes, gating each step on (a) the route actually changing — proves the keypress was
    // captured by Slidev, not the addon UI — and (b) the backend reflecting the new active
    // question. A blind nudge + fixed sleep raced the slide-display observer and could leave the
    // active question stale; the explicit gates make every transition deterministic.
    const navTo = async (key: "ArrowRight" | "ArrowLeft", slide: number, expectedQ: string) => {
      await page.locator(".slidev-page:visible").first().click();
      await page.keyboard.press(key);
      await page.waitForURL(`**/${slide}`, { timeout: 10_000 });
      await expect(async () => {
        expect(await fetchActiveQuestionId(admin, baseURL!, seededData.pollId)).toBe(expectedQ);
      }).toPass({ timeout: 15_000 });
    };

    // Go to Q2 (slide 4) then back to Q1 (slide 3) to fire the activate transitions.
    await navTo("ArrowRight", 4, seededData.q2Id);
    await navTo("ArrowLeft", 3, seededData.q1Id);

    // Q1 panel renders its prompt via the historical snapshot fetch plus the SSE activation event.
    await expect(
      page.locator('[data-testid="poll-results"]', { hasText: "Which JVM for the workshop?" })
    ).toBeVisible({ timeout: 15_000 });

    // Forward to Q2 again, asserting the prompt renders.
    await navTo("ArrowRight", 4, seededData.q2Id);
    await expect(
      page.locator('[data-testid="poll-results"]', { hasText: "Favourite build tool?" })
    ).toBeVisible({ timeout: 10_000 });

    // Back to Q1.
    await navTo("ArrowLeft", 3, seededData.q1Id);
    await expect(
      page.locator('[data-testid="poll-results"]', { hasText: "Which JVM for the workshop?" })
    ).toBeVisible({ timeout: 10_000 });

    expect(pageErrors, `pageerrors: ${pageErrors.join("\n")}`).toEqual([]);
    expect(corsConsoleErrors, `CORS console errors: ${corsConsoleErrors.join("\n")}`).toEqual([]);

    await admin.dispose();
  });

  test("anonymous viewer: follows admin-driven activation without ever POSTing /activate or /close", async ({
    page,
    playwright,
    baseURL
  }) => {
    const pageErrors: string[] = [];
    const corsConsoleErrors: string[] = [];
    page.on("pageerror", (err) => {
      // Slidev's wake-lock plugin throws NotAllowedError in headless Chromium because
      // wakeLock requires a focused page. It's a slidev-runtime concern, not a defect
      // in the deck under test — filter it so the CORS-clean assertion stays useful.
      if (/Wake Lock/i.test(err.message)) return;
      pageErrors.push(err.message);
    });
    page.on("console", (msg) => {
      if (msg.type() !== "error") return;
      if (/CORS|cross-origin|Access-Control/i.test(msg.text())) {
        corsConsoleErrors.push(msg.text());
      }
    });

    // Strip any persisted deck-auth token before the deck boots so the deck is
    // unambiguously anonymous on first paint.
    await page.addInitScript(() => {
      try {
        window.localStorage.removeItem("slidev-polls:deck-auth");
      } catch {
        // safe to ignore in sandboxed contexts
      }
    });

    const activateCalls: string[] = [];
    const closeCalls: string[] = [];
    await page.route("**/api/deck/polls/*/activate", (route) => {
      activateCalls.push(route.request().url());
      return route.continue();
    });
    await page.route("**/api/deck/polls/*/close", (route) => {
      closeCalls.push(route.request().url());
      return route.continue();
    });

    const admin = await playwright.request.newContext({ baseURL });
    await loginAsAlice(admin);

    // Drive the deck externally: open Q1 via admin API, then load slide 3.
    await adminOpen(admin, baseURL!, seededData.pollId, seededData.q1Id);
    await page.goto(`${SLIDEV}/3`);
    await expect(page.getByTestId("poll-results").first()).toBeVisible({ timeout: 30_000 });
    await expect(
      page.locator('[data-testid="poll-results"]', { hasText: "Which JVM for the workshop?" })
    ).toBeVisible({ timeout: 15_000 });

    // The QR-toggle is presenter-only: an anonymous deck must not expose it.
    await expect(page.getByTestId("poll-qr-toggle")).toHaveCount(0);

    // Close Q1, open Q2, navigate to slide 4.
    await adminClose(admin, baseURL!, seededData.pollId);
    await adminOpen(admin, baseURL!, seededData.pollId, seededData.q2Id);
    await page.goto(`${SLIDEV}/4`);
    await expect(
      page.locator('[data-testid="poll-results"]', { hasText: "Favourite build tool?" })
    ).toBeVisible({ timeout: 15_000 });

    // Close Q2, re-open Q1, navigate back to slide 3.
    await adminClose(admin, baseURL!, seededData.pollId);
    await adminOpen(admin, baseURL!, seededData.pollId, seededData.q1Id);
    await page.goto(`${SLIDEV}/3`);
    await expect(
      page.locator('[data-testid="poll-results"]', { hasText: "Which JVM for the workshop?" })
    ).toBeVisible({ timeout: 15_000 });

    expect(activateCalls, `unexpected /activate calls: ${activateCalls.join(",")}`).toEqual([]);
    expect(closeCalls, `unexpected /close calls: ${closeCalls.join(",")}`).toEqual([]);
    expect(pageErrors, `pageerrors: ${pageErrors.join("\n")}`).toEqual([]);
    expect(corsConsoleErrors, `CORS console errors: ${corsConsoleErrors.join("\n")}`).toEqual([]);

    await admin.dispose();
  });

  // Sign the deck in via the nav UI on a normal slide. The deck-auth token is
  // stored in localStorage, shared across same-origin windows — so a presenter
  // window opened afterwards on the same page picks it up.
  async function signInDeck(page: import("@playwright/test").Page) {
    await page.goto(`${SLIDEV}/3`);
    await expect(page.getByTestId("poll-results").first()).toBeVisible({ timeout: 30_000 });
    await page.evaluate(() => window.localStorage.removeItem("slidev-polls:deck-auth"));
    await page.getByTestId("deck-auth-nav-trigger").click();
    await page.getByTestId("deck-auth-username").fill("alice");
    await page.getByTestId("deck-auth-password").fill("correct-horse");
    await page.getByTestId("deck-auth-control").getByRole("button", { name: "sign in" }).click();
    await expect(page.getByTestId("deck-auth-nav-trigger")).toContainText("deck", {
      timeout: 20_000
    });
  }

  test("presenter mode: the next-slide preview does not steal activation from the current question", async ({
    page,
    playwright,
    baseURL
  }) => {
    const admin = await playwright.request.newContext({ baseURL });
    await loginAsAlice(admin);
    // Known starting point: Q1 active.
    await adminOpen(admin, baseURL!, seededData.pollId, seededData.q1Id);

    await signInDeck(page);

    // Enter presenter mode on the Q1 slide (3). Slidev renders the next slide
    // (4 = Q2) as a live `previewNext` component copy. Before the render-context
    // gate, that preview panel reclaimed activation for Q2 on every snapshot —
    // flipping the active question to the not-yet-presented one and making the
    // presenter's view appear stale until a manual refresh.
    await page.goto(`${SLIDEV}/presenter/3`);
    await expect(page.getByTestId("poll-results").first()).toBeVisible({ timeout: 30_000 });

    // The current (presenter-context) panel activates Q1; the preview must not
    // touch the active question. It settles on Q1 and stays there.
    await expect(async () => {
      expect(await fetchActiveQuestionId(admin, baseURL!, seededData.pollId)).toBe(seededData.q1Id);
    }).toPass({ timeout: 15_000 });
    // Hold the window open: a reclaiming preview would flip it to Q2 within a
    // few snapshots. Re-assert after a quiet interval to catch that flap.
    await page.waitForTimeout(3000);
    expect(await fetchActiveQuestionId(admin, baseURL!, seededData.pollId)).toBe(seededData.q1Id);

    await admin.dispose();
  });

  test("presenter mode: a QR overlay toggled in the presenter appears on the audience window", async ({
    page,
    context,
    playwright,
    baseURL
  }) => {
    const admin = await playwright.request.newContext({ baseURL });
    await loginAsAlice(admin);
    await adminOpen(admin, baseURL!, seededData.pollId, seededData.q1Id);

    await signInDeck(page);
    await page.goto(`${SLIDEV}/presenter/3`);
    await expect(page.getByTestId("poll-qr-toggle").first()).toBeVisible({ timeout: 30_000 });

    // Audience window in the SAME browser context — shares the origin and thus
    // the BroadcastChannel the QR sync rides on.
    const audience = await context.newPage();
    await audience.goto(`${SLIDEV}/3`);
    await expect(audience.getByTestId("poll-results").first()).toBeVisible({ timeout: 30_000 });
    await expect(audience.getByTestId("poll-qr-overlay")).toHaveCount(0);

    // Presenter opens the QR; it must appear on the audience screen too — and
    // exactly once. Slidev keeps every slide mounted, so a per-slug sync key
    // would pop one overlay per question panel; the per-question key keeps it
    // to the single on-screen question.
    await page.getByTestId("poll-qr-toggle").first().click();
    await expect(audience.getByTestId("poll-qr-overlay")).toHaveCount(1, { timeout: 10_000 });
    await expect(audience.getByTestId("poll-qr-overlay")).toBeVisible();

    // The overlay must render a scannable QR (an SVG) and print the voter URL
    // (`${pollServer}/${slug}`) so the audience can read or scan it.
    const overlay = audience.getByTestId("poll-qr-overlay");
    await expect(overlay.locator("svg").first()).toBeVisible();
    await expect(overlay).toContainText(seededData.slug);

    // ...and closing it in the presenter clears the audience overlay.
    await page.keyboard.press("Escape");
    await expect(audience.getByTestId("poll-qr-overlay")).toHaveCount(0, { timeout: 10_000 });

    await audience.close();
    await admin.dispose();
  });
});
