#!/usr/bin/env bash
# Seed a demo poll on the running backend and mint a deck token.
# Overwrites examples/slidev-demo/data.ts so slides.md picks up the new
# slug / pollId / questionIds on the next dev-server reload.
#
# Prereqs: backend running at $BASE (default http://localhost:8080), seeded
# admin alice / correct-horse (the dev Spring profile creates it).

set -euo pipefail

BASE="${BASE:-http://localhost:8080}"
HERE="$(cd "$(dirname "$0")/.." && pwd)"
COOKIE_JAR="$(mktemp -t slidev-polls-XXXXXX.jar)"
trap 'rm -f "$COOKIE_JAR"' EXIT

echo "[seed] logging in as alice @ $BASE…"
curl --silent --show-error --fail --cookie-jar "$COOKIE_JAR" \
  -X POST "$BASE/api/admin/login" \
  -H 'content-type: application/json' \
  -d '{"username":"alice","password":"correct-horse"}' >/dev/null

XSRF="$(awk '$6 == "XSRF-TOKEN" {print $7}' "$COOKIE_JAR")"
if [[ -z "$XSRF" ]]; then
  echo "[seed] could not extract XSRF token from cookie jar" >&2
  exit 1
fi

SLUG="demo-$(date +%s)"
# Slidev dev server runs at :3030 by default; allow it as a cross-origin host
# so the deck on :3030 can sign in and stream against the backend on :8080.
DEMO_ORIGIN="${DEMO_ORIGIN:-http://localhost:3030}"
echo "[seed] creating poll with slug $SLUG (allowed origin: $DEMO_ORIGIN)…"
POLL_JSON="$(curl --silent --show-error --fail --cookie "$COOKIE_JAR" \
  -X POST "$BASE/api/admin/polls" \
  -H 'content-type: application/json' \
  -H "X-XSRF-TOKEN: $XSRF" \
  -d "$(cat <<JSON
{
  "title": "Slidev Demo Poll",
  "slug": "$SLUG",
  "allowedOrigins": ["$DEMO_ORIGIN"],
  "questions": [
    {
      "prompt": "Which JVM for the workshop?",
      "options": [
        {"label": "OpenJDK 21"},
        {"label": "GraalVM"},
        {"label": "Azul Zulu"}
      ]
    },
    {
      "prompt": "Favourite build tool?",
      "options": [
        {"label": "Maven"},
        {"label": "Gradle"},
        {"label": "Bazel"}
      ]
    }
  ]
}
JSON
)")"

POLL_ID="$(printf '%s' "$POLL_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["id"])')"
Q1_ID="$(printf '%s' "$POLL_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["questions"][0]["id"])')"
Q2_ID="$(printf '%s' "$POLL_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["questions"][1]["id"])')"

echo "[seed] minting deck token…"
TOKEN_JSON="$(curl --silent --show-error --fail --cookie "$COOKIE_JAR" \
  -X POST "$BASE/api/admin/polls/$POLL_ID/deck-tokens" \
  -H 'content-type: application/json' \
  -H "X-XSRF-TOKEN: $XSRF" \
  -d '{"label":"demo-deck"}')"
TOKEN_PLAIN="$(printf '%s' "$TOKEN_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["plaintext"])')"

cat >"$HERE/data.ts" <<TS
// Generated by scripts/seed.sh at $(date --iso-8601=seconds).
// Safe to regenerate; checked in only as a placeholder stub.
import { configureDeckAuthBackend } from "@polls/slidev-addon";

export const pollServer = "$BASE";
export const pollSlug = "$SLUG";
export const pollId = "$POLL_ID";
export const q1Id = "$Q1_ID";
export const q2Id = "$Q2_ID";

// Side-effect: route in-deck auth (sign-in + verify) at the backend instead
// of the slidev dev server. Importing this module from any slide is enough.
configureDeckAuthBackend(pollServer);
TS

echo
echo "[seed] slug          : $SLUG"
echo "[seed] poll id       : $POLL_ID"
echo "[seed] question 1 id : $Q1_ID"
echo "[seed] question 2 id : $Q2_ID"
echo "[seed] deck token    : $TOKEN_PLAIN"
echo
echo "[seed] wrote $HERE/data.ts"
echo "[seed] next:"
echo "  1) bun run slidev          (from examples/slidev-demo)"
echo "  2) paste the deck token into the auth control (top-right)"
echo "  3) navigate to slide 3 and 4 — watch /api/deck/.../activate fire"
echo "  4) vote at $BASE/$SLUG  to watch live tallies update"
