// Generated by scripts/seed.sh at 2026-04-21T23:09:00+02:00.
// Safe to regenerate; checked in only as a placeholder stub.
export const pollServer = "http://localhost:8080";
export const pollSlug = "demo-1776805740";
export const pollId = "efb25d57-fc62-42d5-851b-4158f193710c";
export const q1Id = "78feab1c-c536-4f5e-a44b-fe2fc399d594";
export const q2Id = "5cfd1208-9965-4ba9-baa4-483e1dd8c959";
